### ISSUE TITLE
Add conversion test service banner

### ISSUE THREAD

**Issue by thijsdevalk** [Yoast/convert-experiments#7]
![managing_tests](https://f.cloud.github.com/assets/3940508/2281943/b40e9636-9fa5-11e3-9b25-94124bfedb2b.png)
![managing_tests_x2](https://f.cloud.github.com/assets/3940508/2281945/b6632dc0-9fa5-11e3-9694-1194c62be832.png)

Link to: https://yoast.com/hire-us/conversion-test-management/?utm_source=yoast-convert-config&utm_medium=banner&utm_campaign=manage-tests-banner

**Comment by jdevalk** [comment]
We no longer want this.
